version: '3.8'

services:
  db:
    build: .
    container_name: devtraining-db
    restart: always
    ports:
      - 5430:5432
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=devtraining

  dbtest:
    build: .
    container_name: db-test
    restart: always
    ports:
      - 5429:5432
    environment:
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=devtraining
